### ISSUE TITLE
State status appears to be reversed until cycled

### ISSUE THREAD

**Issue by BUMPRW** [mlamoure/Indigo-August-Home#1]
I installed my August Smart Lock pro with the connect feature yesterday.  I get an accurate state status with the August app, but using the plugin in Indigo 7, you must cycle the lock from Indigo to get an accurate state, it does not seem to get an accurate state without doing so.  I had the plugin running for several hours and the state was showing unlocked while the lock was actually locked.  I then cycled the lock and the state provided an accurate status.

**Comment by mlamoure** [comment]
Hi-

Happy to help.  This should not be happening.  Though, before we get into it, I recommend you try to add your August Pro as a direct Z-Wave device rather than using my plugin.  This is the far better way to go.  My plugin was designed for the non Z-Wave version, where cloud is the only option to get the state.

If you prefer to use my plugin, I can help debug.  I'm sure it has something to do with the Pro being slightly different.  Certainly you should be getting state updates that occur outside of Indigo.

Let me know what you decide.  I would also like to hear if you do get the August working directly via Z-Wave.  I've heard of a few people trying it, but no one has confirmed that it is working.  Jay and Matt indicate it should work.

Mike

**Comment by BUMPRW** [comment]
Mike,

    It is working fine now.  For some reason I had to do an initial open/close to get the status.  So far I have been unsuccessful with a Z-wave hook up and I have Items directly adjacent to the front door.  It just won’t synch.  I just wanted to let you know there was a little glitch that required some sort of interaction.
    I also have the connect module that allows local control.  August handles that as a separate device, probably to handle multiple locks.

Richard

**Comment by mlamoure** [comment]
Interesting.  Would you be willing to debug the Z-Wave hook up with the Indigo guys?  If you got it working, I would be interested in buying one myself for a couple of reasons:

1. I would try to fix the errors that you experienced.  You are the second person to bring them up and it's hard for me to fix at a distance.

2. I would be interested in advancing the plugin to stay relevant, where my plugin would handle lock events, such as Lock/Unlock by known person, but defer the lock status to Indigo.
